# Generated by Django 3.0.5 on 2025-03-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_type', models.CharField(default='less', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_eng', models.CharField(max_length=255, null=True)),
                ('product_name_guj', models.CharField(max_length=255, null=True)),
                ('product_name_hin', models.CharField(max_length=255, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='Product_images/%Y%m%d/%H%M%S/')),
                ('product_qty', models.CharField(max_length=255, null=True)),
                ('product_unit', models.CharField(max_length=255, null=True)),
                ('product_gst_rate', models.IntegerField(default=0)),
                ('product_discount_rate', models.IntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_hsn_code', models.CharField(max_length=255, null=True)),
                ('is_delete', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'Customer'), ('1', 'Admin')], default='0', max_length=15)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('shopname', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('register_by', models.CharField(default='self', max_length=255, null=True)),
                ('is_approved', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('expo_go_token', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('holderName', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('account_num', models.CharField(blank=True, max_length=255, null=True)),
                ('fassai', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='order_taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(blank=True, max_length=255, null=True)),
                ('cgst_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('sgst_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.Order')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.Products')),
            ],
            options={
                'db_table': 'Orders_list',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vardhaman.User'),
        ),
    ]
