# Generated by Django 4.2.5 on 2025-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_eng', models.CharField(max_length=255, null=True)),
                ('product_name_guj', models.CharField(max_length=255, null=True)),
                ('product_name_hin', models.CharField(max_length=255, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='Product_images/%Y%m%d/%H%M%S/')),
                ('product_qty', models.CharField(max_length=255, null=True)),
                ('product_unit', models.CharField(max_length=255, null=True)),
                ('product_gst_rate', models.IntegerField(default=0)),
                ('product_discount_rate', models.IntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_hsn_code', models.CharField(max_length=255, null=True)),
                ('is_delete', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'Customer'), ('1', 'Admin')], default='0', max_length=15)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('shopname', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('register_by', models.CharField(default='self', max_length=255, null=True)),
                ('is_approved', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('expo_go_token', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('holderName', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('account_num', models.CharField(blank=True, max_length=255, null=True)),
                ('fassai', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
