# Generated by Django 4.2.5 on 2024-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('0', 'Customer'), ('1', 'Admin')], default='0', max_length=15)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact_no', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_approved', models.CharField(default=False, max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
