# Generated by Django 4.2.5 on 2025-03-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_type', models.CharField(default='less', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vardhaman.user')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='order_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(blank=True, max_length=255, null=True)),
                ('cgst_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('sgst_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.order')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.products')),
            ],
            options={
                'db_table': 'Orders_list',
            },
        ),
    ]
