# Generated by Django 4.2.5 on 2024-01-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type_of',
            new_name='role',
        ),
    ]
