# Generated by Django 3.1.12 on 2026-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('items_list', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
