# Generated by Django 4.2.5 on 2024-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0002_rename_type_of_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_eng', models.CharField(max_length=255)),
                ('product_name_guj', models.CharField(max_length=255)),
                ('product_name_hin', models.CharField(max_length=255)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='files/%Y%m%d/%H%M%S/')),
                ('product_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('product_qty', models.CharField(max_length=255)),
                ('product_price', models.FloatField(default=0.0, max_length=20)),
                ('product_hsn_code', models.CharField(max_length=255)),
            ],
        ),
    ]
