# Generated by Django 3.1.12 on 2026-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0002_esstimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='esstimate',
            name='grand_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
