# Generated by Django 4.2.5 on 2024-01-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image_url',
        ),
    ]
