# Generated by Django 4.2.5 on 2024-01-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0006_products_created_at_products_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
