# Generated by Django 4.2.5 on 2024-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0010_user_firebase_token_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
