# Generated by Django 4.2.5 on 2024-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0012_order_order_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order_data',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10),
        ),
        migrations.AlterModelTable(
            name='order_data',
            table='Orders_list',
        ),
    ]
