# Generated by Django 4.2.5 on 2024-01-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0013_remove_order_updated_at_order_data_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_data',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_data',
        ),
    ]
