# Generated by Django 4.2.5 on 2024-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0016_rename_amount_order_total_amount_order_data_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10),
        ),
    ]
