# Generated by Django 4.2.5 on 2024-01-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0017_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
