# Generated by Django 4.2.5 on 2024-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0018_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=10),
        ),
    ]
