# Generated by Django 4.2.5 on 2024-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0019_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
