# Generated by Django 4.2.5 on 2024-03-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0021_order_amount_order_cgst_amount_order_sgst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vardhaman.user'),
        ),
    ]
