# Generated by Django 4.2.5 on 2024-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0022_alter_order_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_GST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_tax_price',
            field=models.IntegerField(default=0),
        ),
    ]
