# Generated by Django 4.2.5 on 2024-03-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0023_order_buyer_gst_order_buyer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_discount',
            new_name='product_discount_rate',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_gst',
            new_name='product_gst_rate',
        ),
    ]
