# Generated by Django 4.2.5 on 2024-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0024_rename_product_discount_products_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_tax_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
