# Generated by Django 4.2.5 on 2024-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0025_alter_products_product_tax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
