# Generated by Django 4.2.5 on 2024-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0026_order_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_GST',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_name',
        ),
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=10),
        ),
    ]
