# Generated by Django 4.2.5 on 2024-03-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0029_order_data_cgst_amount_order_data_cgst_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
