# Generated by Django 4.2.5 on 2024-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0030_remove_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='round_type',
            field=models.CharField(default='less', max_length=255),
        ),
    ]
