# Generated by Django 4.2.5 on 2024-03-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0031_order_round_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sgst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.CreateModel(
            name='order_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vardhaman.order')),
            ],
        ),
    ]
