# Generated by Django 4.2.5 on 2024-03-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0035_user_account_num_user_bankname_user_fassai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
