# Generated by Django 4.2.5 on 2024-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0036_user_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopname',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
