# Generated by Django 4.2.5 on 2024-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0037_user_shopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
