# Generated by Django 4.2.5 on 2024-04-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0039_order_address_order_contact_no_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
