# Generated by Django 4.2.5 on 2024-04-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0040_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
