# Generated by Django 4.2.5 on 2024-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0041_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_by',
            field=models.CharField(default='self', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
