# Generated by Django 4.2.5 on 2024-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardhaman', '0042_user_register_by_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
